package ERCare;


/**
* ERCare/PatientValuesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Messages.idl
* Monday, December 9, 2013 11:30:07 AM CET
*/

public final class PatientValuesHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public PatientValuesHolder ()
  {
  }

  public PatientValuesHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ERCare.PatientValuesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ERCare.PatientValuesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ERCare.PatientValuesHelper.type ();
  }

}
