package ERCare;


/**
* ERCare/SubmitData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Messages.idl
* Monday, December 9, 2013 11:06:22 AM CET
*/

public interface SubmitData extends SubmitDataOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SubmitData
