package ERCare;


/**
* ERCare/AlarmConfigurationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerAlarmConfig.idl
* Thursday, December 5, 2013 3:31:07 PM CET
*/

abstract public class AlarmConfigurationHelper
{
  private static String  _id = "IDL:ERCare/AlarmConfiguration:1.0";

  public static void insert (org.omg.CORBA.Any a, ERCare.AlarmConfiguration that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ERCare.AlarmConfiguration extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [9];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "minSBP",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "maxSBP",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "minDBP",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "maxDBP",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "minHRP",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "maxHRP",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[6] = new org.omg.CORBA.StructMember (
            "minSAT",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[7] = new org.omg.CORBA.StructMember (
            "maxSAT",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "PatID",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ERCare.AlarmConfigurationHelper.id (), "AlarmConfiguration", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ERCare.AlarmConfiguration read (org.omg.CORBA.portable.InputStream istream)
  {
    ERCare.AlarmConfiguration value = new ERCare.AlarmConfiguration ();
    value.minSBP = istream.read_long ();
    value.maxSBP = istream.read_long ();
    value.minDBP = istream.read_long ();
    value.maxDBP = istream.read_long ();
    value.minHRP = istream.read_long ();
    value.maxHRP = istream.read_long ();
    value.minSAT = istream.read_long ();
    value.maxSAT = istream.read_long ();
    value.PatID = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ERCare.AlarmConfiguration value)
  {
    ostream.write_long (value.minSBP);
    ostream.write_long (value.maxSBP);
    ostream.write_long (value.minDBP);
    ostream.write_long (value.maxDBP);
    ostream.write_long (value.minHRP);
    ostream.write_long (value.maxHRP);
    ostream.write_long (value.minSAT);
    ostream.write_long (value.maxSAT);
    ostream.write_string (value.PatID);
  }

}
