package ERCare;


/**
* ERCare/MeasurementStructureHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ERCare.idl
* Thursday, December 5, 2013 3:18:31 PM CET
*/

abstract public class MeasurementStructureHelper
{
  private static String  _id = "IDL:ERCare/MeasurementStructure:1.0";

  public static void insert (org.omg.CORBA.Any a, ERCare.MeasurementStructure that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ERCare.MeasurementStructure extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "SBP",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "DBP",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "HRP",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "SAT",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "PatID",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "timestamp",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ERCare.MeasurementStructureHelper.id (), "MeasurementStructure", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ERCare.MeasurementStructure read (org.omg.CORBA.portable.InputStream istream)
  {
    ERCare.MeasurementStructure value = new ERCare.MeasurementStructure ();
    value.SBP = istream.read_long ();
    value.DBP = istream.read_long ();
    value.HRP = istream.read_long ();
    value.SAT = istream.read_long ();
    value.PatID = istream.read_string ();
    value.timestamp = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ERCare.MeasurementStructure value)
  {
    ostream.write_long (value.SBP);
    ostream.write_long (value.DBP);
    ostream.write_long (value.HRP);
    ostream.write_long (value.SAT);
    ostream.write_string (value.PatID);
    ostream.write_long (value.timestamp);
  }

}
