package ERCare;

/**
* ERCare/MeasurementStructureHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ERCare.idl
* Thursday, December 5, 2013 3:18:31 PM CET
*/

public final class MeasurementStructureHolder implements org.omg.CORBA.portable.Streamable
{
  public ERCare.MeasurementStructure value = null;

  public MeasurementStructureHolder ()
  {
  }

  public MeasurementStructureHolder (ERCare.MeasurementStructure initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ERCare.MeasurementStructureHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ERCare.MeasurementStructureHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ERCare.MeasurementStructureHelper.type ();
  }

}
