// IDL
module ERCare {
	struct MeasurementStructure {
		long SBP;
		long DBP;
		long HRP;
		long SAT;
		string PatID;
		long timestamp; 
	};
	
	typedef sequence<MeasurementStructure> MeasurementStructures;
};