// IDL
module ERCare {
	struct AlarmConfiguration {
		long minSBP;
		long maxSBP;
		long minDBP;
		long maxDBP;
		long minHRP;
		long maxHRP;
		long minSAT;
		long maxSAT;
		string PatID;
	};
	
	typedef sequence<AlarmConfiguration> AlarmConfigurationS;
};