package ERCare;


/**
* ERCare/AlarmConfiguration.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerAlarmConfig.idl
* Thursday, December 5, 2013 3:31:07 PM CET
*/

public final class AlarmConfiguration implements org.omg.CORBA.portable.IDLEntity
{
  public int minSBP = (int)0;
  public int maxSBP = (int)0;
  public int minDBP = (int)0;
  public int maxDBP = (int)0;
  public int minHRP = (int)0;
  public int maxHRP = (int)0;
  public int minSAT = (int)0;
  public int maxSAT = (int)0;
  public String PatID = null;

  public AlarmConfiguration ()
  {
  } // ctor

  public AlarmConfiguration (int _minSBP, int _maxSBP, int _minDBP, int _maxDBP, int _minHRP, int _maxHRP, int _minSAT, int _maxSAT, String _PatID)
  {
    minSBP = _minSBP;
    maxSBP = _maxSBP;
    minDBP = _minDBP;
    maxDBP = _maxDBP;
    minHRP = _minHRP;
    maxHRP = _maxHRP;
    minSAT = _minSAT;
    maxSAT = _maxSAT;
    PatID = _PatID;
  } // ctor

} // class AlarmConfiguration
