package ERCare;


/**
* ERCare/AlarmConfigurationSHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerAlarmConfig.idl
* Thursday, December 5, 2013 3:31:07 PM CET
*/

abstract public class AlarmConfigurationSHelper
{
  private static String  _id = "IDL:ERCare/AlarmConfigurationS:1.0";

  public static void insert (org.omg.CORBA.Any a, ERCare.AlarmConfiguration[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ERCare.AlarmConfiguration[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ERCare.AlarmConfigurationHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ERCare.AlarmConfigurationSHelper.id (), "AlarmConfigurationS", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ERCare.AlarmConfiguration[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ERCare.AlarmConfiguration value[] = null;
    int _len0 = istream.read_long ();
    value = new ERCare.AlarmConfiguration[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ERCare.AlarmConfigurationHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ERCare.AlarmConfiguration[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ERCare.AlarmConfigurationHelper.write (ostream, value[_i0]);
  }

}
