// IDL
module ERCare {
	
	typedef sequence<long> PatientValues;
	
	interface SubmitData{
		oneway void SBPData(in string patientID, in long value);
		oneway void DBPData(in string PatientID, in long value);
		oneway void HRPData(in string PatientID, in long value);
		oneway void SatData(in string PatientID, in long value);
		oneway void SetMinThreshold(in string patientID, in string dataType, in long value);
		oneway void SetMaxThreshold(in string patientID, in string dataType, in long value);
		PatientValues GetValues(in string patientID, in string dataType);
	};
	
		
};