package ERCare;

/**
* ERCare/AlarmHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmType.idl
* Wednesday, December 11, 2013 1:20:22 PM CET
*/

public final class AlarmHolder implements org.omg.CORBA.portable.Streamable
{
  public ERCare.Alarm value = null;

  public AlarmHolder ()
  {
  }

  public AlarmHolder (ERCare.Alarm initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ERCare.AlarmHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ERCare.AlarmHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ERCare.AlarmHelper.type ();
  }

}
