package ERCare;


/**
* ERCare/Alarm.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmType.idl
* Wednesday, December 11, 2013 1:20:22 PM CET
*/

public final class Alarm implements org.omg.CORBA.portable.IDLEntity
{
  public int alarmType = (int)0;
  public int alarmValue = (int)0;

  public Alarm ()
  {
  } // ctor

  public Alarm (int _alarmType, int _alarmValue)
  {
    alarmType = _alarmType;
    alarmValue = _alarmValue;
  } // ctor

} // class Alarm
