package ERCare;


/**
* ERCare/MeasurementStructuresHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ERCare.idl
* Wednesday, December 11, 2013 1:20:27 PM CET
*/

public final class MeasurementStructuresHolder implements org.omg.CORBA.portable.Streamable
{
  public ERCare.MeasurementStructure value[] = null;

  public MeasurementStructuresHolder ()
  {
  }

  public MeasurementStructuresHolder (ERCare.MeasurementStructure[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ERCare.MeasurementStructuresHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ERCare.MeasurementStructuresHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ERCare.MeasurementStructuresHelper.type ();
  }

}
