package ERCare;

/**
* ERCare/PatientValuesStructureHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SubscribePatient.idl
* Thursday, December 5, 2013 3:31:10 PM CET
*/

public final class PatientValuesStructureHolder implements org.omg.CORBA.portable.Streamable
{
  public ERCare.PatientValuesStructure value = null;

  public PatientValuesStructureHolder ()
  {
  }

  public PatientValuesStructureHolder (ERCare.PatientValuesStructure initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ERCare.PatientValuesStructureHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ERCare.PatientValuesStructureHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ERCare.PatientValuesStructureHelper.type ();
  }

}
